### ISSUE TITLE
my own dataset error

### ISSUE THREAD

**Issue by tanshao111** [BNN-UPC/TwinNet#3]
Dear Miquel,

I hope this message finds you well. Recently, I've been looking to generate my own dataset and test it using the TwinNet model. I've noticed the bnnupc's open-source BNNetSimulator and have used it to generate a dataset. However, when I attempted to use this dataset as a test set, I encountered the following error.
![自己的数据集有问题](https://github.com/user-attachments/assets/282842f8-0df0-404b-ab28-7b41d035793c)

I've observed that the issue might stem from differences in the Datanet API across various versions of the dataset. To further test, I attempted to apply the RouteNet-Fermi model but encountered similar issues. Moreover, it's challenging to reconcile training and testing datasets if they are not aligned in terms of Datanet API versions. If I wish to continue training with the NSFNet dataset but test with my own generated dataset, how should I proceed?

Best regards,
tanshao111

**Comment by albert-lopez** [comment]
Dear tanshao111
If you have to work with several datasets with different APIs, then you can do the following:
If we have for instance these two datasets:  /data/synth/dataset1  /data/real/dataset2

import sys
import importlib

sys.path.insert(0,"/data")

api_pkg_1 =  "synth.dataset1.datanetAPI"
api_module_1 = importlib.import_module(api_pkg_1)
it_1 = iter(api_module_1.DatanetAPI(" /data/synth/dataset1"))
for s in it_1:
    ...

api_pkg_2 =  "real.dataset2.datanetAPI"
api_module_2 = importlib.import_module(api_pkg_2)
it_2 = iter(api_module_2.DatanetAPI(" /data/real/dataset2"))
for s in it_2:
    ...

I hope this example helps you to solve the problem.

Best regards

Albert
